new_pipeline_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: public

#Aqui estou dizendo ao dbt para se conectar ao banco PostgreSQL que roda dentro do Docker
#Esse banco será criado automaticamente quando montar o docker-compose